name: Wordle
targets:
  Wordle:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Wordle
    resources:
      - Wordle/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.wordleios
        SWIFT_VERSION: 5.9
        INFOPLIST_FILE: Wordle/Info.plist
